# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://naco-siren.github.io
date_format: "ordinal"
title: Naco Siren
subtitle: "尹小晗的个人博客"
description: "尹小晗的个人博客"
keywords: naco-siren, Naco Siren
timezone: US/Pacific
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Naco Siren
organization: Wish.com
organization_url: https://www.wish.com
github_username: naco-siren
location: San Francisco, US
email: hanyin2@illinois.edu

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: naco-siren/naco-siren.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: naco-siren
    repo: blog-comments
    oauth:
        client_id: 7d21b26fb1d7b27a313b
        client_secret: 88143d2c1593cda56ea7bb30f6c07099aa33d3b8
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: naco-siren
    repo: blog-comments
    clientID: 7d21b26fb1d7b27a313b
    clientSecret: 88143d2c1593cda56ea7bb30f6c07099aa33d3b8
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-112850675-1
